### ISSUE TITLE
it take stime to install

### ISSUE THREAD

**Issue by Glitchesminds** [haydenbanz/SpeechStylis#6]
it took me 30 mins to generate cloned voice.

**Comment by haydenbanz** [comment]
its better to upgrade cpu to gpu or else u can this repo in google collab or hugging face

**Comment by haydenbanz** [comment]
ts better to upgrade cpu to gpu or else u can this repo in google collab or hugging face

**Comment by haydenbanz** [comment]
ts better to upgrade cpu to gpu or else u can this repo in google collab or hugging face
